services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.55.0-jammy
    container_name: cc_playwright
    working_dir: /workspace/cc-webapp/frontend
    environment:
      BASE_URL: http://frontend:3000
      API_BASE_URL: http://backend:8000
      # Admin bearer for admin specs (optional; specs will skip if missing)
      E2E_ADMIN_BEARER: ${E2E_ADMIN_BEARER:-}
      ADMIN_BEARER: ${ADMIN_BEARER:-}
      ADMIN_TOKEN: ${ADMIN_TOKEN:-}
      # Invite code for signup flows (optional)
      E2E_INVITE_CODE: ${E2E_INVITE_CODE:-"5858"}
      CI: "1"
      HEADLESS: "1"
    volumes:
      - ./:/workspace
      - ./logs/playwright:/workspace/cc-webapp/frontend/test-results:rw
      - playwright_node_modules:/workspace/cc-webapp/frontend/node_modules
    depends_on:
      - frontend
      - backend
    networks: [ccnet]
    entrypoint: ["bash", "-lc", "npm ci --no-audit --no-fund || npm install --no-audit --no-fund; npx playwright install --with-deps; npx playwright test --config=playwright.config.ts"]

networks:
  ccnet:
    external: true

volumes:
  playwright_node_modules:
