# Docker Compose에 테스트 서비스 추가

version: '3.8'

services:
  # 기존 서비스들은 유지...
  
  # API 연동 테스트 서비스
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: cc_api_tests
    depends_on:
      - backend
      - postgres
      - redis
    environment:
      - API_BASE_URL=http://backend:8000
      - PYTHONPATH=/app
    volumes:
      - ./test-results:/app/test-results
      - ./test_api_integration.py:/app/test_api_integration.py
      - ./test-requirements.txt:/app/test-requirements.txt
    networks:
      - ccnet
    command: ["pytest", "/app/test_api_integration.py", "-v", "--html=/app/test-results/report.html", "--json-report", "--json-report-file=/app/test-results/report.json"]
