version: "3.8"

services:
  frontend:
    build:
      context: ./cc-webapp/frontend
      dockerfile: Dockerfile.dev
    container_name: cc_frontend_temp
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://host.docker.internal:8000}
    volumes:
      - ./cc-webapp/frontend:/app
      - ./logs/frontend:/app/logs:rw
      - /app/node_modules
    ports:
      - "3000:3000"
    command: ["sh","-c","npm ci || npm install && npm run dev -- -H 0.0.0.0"]
    networks:
      - frontend-net

networks:
  frontend-net:
    driver: bridge
