version: '3.8'

services:
  postgres:
    ports:
      - "5432:5432"

  backend:
    volumes:
      - ./cc-webapp/backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    volumes:
      - ./cc-webapp/frontend:/app
    environment:
      NODE_ENV: development
    command: npm run dev

  pgadmin:
    image: dpage/pgadmin4
    container_name: cc-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@casino-club.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
