services:
  backend:
    container_name: cc_backend_local

  frontend:
    container_name: cc_frontend_local
    environment:
      NEXT_PUBLIC_API_URL: "${NEXT_PUBLIC_API_URL:-http://localhost:8000}"

  postgres:
    container_name: cc_postgres_local

  redis:
    container_name: cc_redis_local

  kafka:
    container_name: cc_kafka_local

  zookeeper:
    container_name: cc_zookeeper_local
