name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: cc_webapp
          POSTGRES_USER: cc_user
          POSTGRES_PASSWORD: cc_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        working-directory: cc-webapp/backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint & Unit (smoke)
        working-directory: cc-webapp/backend
        env:
          POSTGRES_SERVER: localhost
          POSTGRES_USER: cc_user
          POSTGRES_PASSWORD: cc_password
          POSTGRES_DB: cc_webapp
          CI_CRASH_BLOCKING: ${{ env.CI_CRASH_BLOCKING }}
        run: |
          if [ "${CI_CRASH_BLOCKING}" = "1" ]; then \
            python -m pytest -q app/tests/test_auth.py; \
            python -m pytest -q app/tests/test_crash_edge_cases.py; \
            python -m pytest -q app/tests/test_crash_session_lifecycle.py; \
          else \
            python -m pytest -q app/tests/test_auth.py || true; \
            python -m pytest -q app/tests/test_crash_edge_cases.py || true; \
            python -m pytest -q app/tests/test_crash_session_lifecycle.py || true; \
          fi

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        working-directory: cc-webapp/frontend
        run: npm ci || npm i
      - name: Type check
        working-directory: cc-webapp/frontend
        run: npx tsc --noEmit
      - name: Lint
        working-directory: cc-webapp/frontend
        run: npm run lint || echo "skip lint"
      - name: Test
        working-directory: cc-webapp/frontend
        run: npm test -- --ci
