name: Frontend Production Build (Env Guard)
# 이 워크플로우는 프론트 prod 빌드 시 필수 ENV(NEXT_PUBLIC_API_BASE/ORIGIN)를 강제합니다.

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'cc-webapp/frontend/**'
      - '.github/workflows/frontend-build.yml'
  push:
    branches: [ main ]
    paths:
      - 'cc-webapp/frontend/**'
      - '.github/workflows/frontend-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cc-webapp/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: cc-webapp/frontend/package-lock.json

      - name: Install dependencies
        run: npm ci --no-audit --no-fund || npm i --no-audit --no-fund

      - name: Production build (env guarded)
        env:
          NODE_ENV: production
          NEXT_PUBLIC_API_BASE: http://localhost:8000
          NEXT_PUBLIC_API_ORIGIN: http://localhost:8000
        run: npm run build
